CREATE_USER_TABLE_QUERY = """
        CREATE TABLE IF NOT EXISTS telegram_users
        (ID INTEGER PRIMARY KEY,
         TELEGRAM_ID INTEGER,
         USERNAME CHAR(50),
         FIRST_NAME CHAR(50),
         LAST_NAME CHAR(50),
         UNIQUE(TELEGRAM_ID)
         )
"""

INSERT_USER_QUERY = """INSERT OR IGNORE INTO telegram_users VALUES (?,?,?,?,?)"""

CREATE_RESPONSES_TABLE_QUERY = """
        CREATE TABLE IF NOT EXISTS user_responses
        (ID INTEGER PRIMARY KEY,
         TELEGRAM_ID INTEGER,
         RESPONSE_TEXT TEXT,
         FOREIGN KEY (TELEGRAM_ID) REFERENCES telegram_users(TELEGRAM_ID)
         )
"""
INSERT_RESPONSE_QUERY = """INSERT INTO user_responses (TELEGRAM_ID, RESPONSE_TEXT) VALUES (?, ?)"""
